apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-unseal-bun
  namespace: infra
  labels:
    app: vault-unseal-bun
spec:
  replicas: 1  
  revisionHistoryLimit: 2
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: vault-unseal-bun
  template:
    metadata:
      labels:
        app: vault-unseal-bun
      annotations:
        consul.hashicorp.com/connect-inject: "false"  # ปิด Consul injection
        # vault.hashicorp.com/agent-inject: "true"
        # vault.hashicorp.com/agent-inject-token: "true"
        # vault.hashicorp.com/agent-pre-populate-only: "true" # comment เพื่อเอา sidecar
        # vault.hashicorp.com/agent-inject-token-volume: "/vault"
        # vault.hashicorp.com/role: "backend-rpubkey"
    spec:
      serviceAccountName: vault-unseal-bun
      dnsPolicy: ClusterFirst
      containers:
      - name: vault-unseal-bun
        image: registry.registry.svc.cluster.local:5000/vault-unseal-bun:6
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always