apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: vault-unseal-bun-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"

spec:
  ingressClassName: nginx
  tls:
    - secretName: vault-unseal-bun-ingress-tls
      hosts:
        - vault.tarchunk.win
  rules:
    - host: vault.tarchunk.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-unseal-bun-service
                port:
                  number: 3000
