apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: chat-to-tar-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # เปลี่ยนเป็น HTTPS
    nginx.ingress.kubernetes.io/backend-https-verify: "false"  # ปิด verify เพราะ self-signed
    # ปิด cert-manager ไม่ให้แทรกแซง
    # cert-manager.io/issuer: ""
    # cert-manager.io/cluster-issuer: ""
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"

spec:
  ingressClassName: nginx
  tls:
    - secretName: chat-to-tar-ingress-tls
      hosts:
        - chat.tarchunk.win
  rules:
    - host: chat.tarchunk.win        # ✅ ต้องเป็น 'host' ไม่ใช่ 'hosts'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-to-tar
                port:
                  number: 443
