apiVersion: v1
kind: Service
metadata:
  name: sso-fe
  namespace: infra
spec:
  selector:
    app: sso-fe
  ports:
  - name: metrics
    port: 443
    targetPort: 443 
    protocol: TCP
  type: LoadBalancer