apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-rpubkey
  namespace: web-pubkey
  labels:
    app: backend-rpubkey
spec:
  replicas: 2  
  revisionHistoryLimit: 2
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: backend-rpubkey
  template:
    metadata:
      labels:
        app: backend-rpubkey
      annotations:
        consul.hashicorp.com/connect-inject: "false"  # ปิด Consul injection
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        # vault.hashicorp.com/agent-pre-populate-only: "true" # comment เพื่อเอา sidecar
        vault.hashicorp.com/agent-inject-token-volume: "/vault"
        vault.hashicorp.com/role: "backend-rpubkey"
    spec:
      serviceAccountName: backend-rpubkey
      dnsPolicy: ClusterFirst
      containers:
      - name: backend-rpubkey
        image: registry.registry.svc.cluster.local:5000/backend-rpubkey:17
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always