apiVersion: v1
kind: Service
metadata:
  name: backend-rpubkey-service
  namespace: web-pubkey
  labels:
    app: backend-rpubkey
spec:
  selector:
    app: backend-rpubkey
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP