apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: sso-backend-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # เปลี่ยนเป็น HTTPS
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"

spec:
  ingressClassName: nginx
  tls:
    - secretName: sso-backend-ingress-tls
      hosts:
        - sso-backend.tarchunk.win
  rules:
    - host: sso-backend.tarchunk.win        # ✅ ต้องเป็น 'host' ไม่ใช่ 'hosts'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sso-bun-service
                port:
                  number: 3000
