apiVersion: v1
kind: Service
metadata:
  name: sso-bun-service
  namespace: infra
  labels:
    app: sso-bun
spec:
  selector:
    app: sso-bun
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer